[[steps]]
name = "Setup go"
command = ["fluentci run --wasm pkgx install go"]

[[steps]]
name = "go get & build"
command = ["go get", "go build -o ./bin/main"]

[[steps]]
name = "Check code style"
command = ["gofmt main.go | diff --ignore-tab-expansion main.go -"]

[[steps]]
name = "Run tests"
command = [
  "fluentci run --wasm postgres start",
  "go install gotest.tools/gotestsum@latest",
  "PATH=$HOME/go/bin:$PATH gotestsum --junitfile junit.xml ./...",
]
env = ["POSTGRES_USER=postgres", "POSTGRES_DB=s2"]

[[steps]]
name = "Test web server"
command = [
  "./bin/main 8001 &",
  "curl --silent localhost:8001/time | grep \"The current time is\"",
]
